const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('desktopAPI', {
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  gpuInfo: () => ipcRenderer.invoke('gpu-info'),
  resetScan: () => ipcRenderer.invoke('reset-scan'),
  listFolder: id => ipcRenderer.invoke('list-folder', id),
  validateFile: id => ipcRenderer.invoke('validate-file', id),
  hashFile: id => ipcRenderer.invoke('hash-file', id),
  getCachedFile: id => ipcRenderer.invoke('get-cached-file', id),
  cacheVisual: (id, visual) => ipcRenderer.invoke('cache-visual', id, visual),
  listSessions: () => ipcRenderer.invoke('list-sessions'),
  beginSession: items => ipcRenderer.invoke('begin-session', items),
  saveSession: (id, patch) => ipcRenderer.invoke('save-session', id, patch),
  loadSession: id => ipcRenderer.invoke('load-session', id),
  refreshSession: id => ipcRenderer.invoke('refresh-session', id),
  forgetSession: id => ipcRenderer.invoke('forget-session', id),
  confirmRemoval: ids => ipcRenderer.invoke('confirm-removal', ids),
  trashFile: id => ipcRenderer.invoke('trash-file', id),
  smokeTest: process.argv.includes('--dup-smoke'),
  reportSmoke: result => ipcRenderer.invoke('smoke-result', result),
  mutateSmokeFixtures: png => ipcRenderer.invoke('mutate-smoke-fixtures', png),
});
